# Don't print a new line
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[aws]
format = 'on [$symbol$profile(\($region\))]($style) '
style = "bold blue"
symbol = "ğŸ…° "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[dotnet]
symbol = "dotnet"
style = "green"
heuristic = false

[git_commit]
commit_hash_length = 4
tag_symbol = "git commit"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[CHERRY PICKING](bold red)"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸahead"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "untracked"
stashed = "ğŸ“¦"
modified = "modified"
staged = '[++\($count\)](green)'
renamed = "git status"
deleted = "ğŸ—‘"

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"

[line_break]
disabled = true

[lua]
format = "via [ğŸŒ• $version](bold blue) "
